### PR TITLE
W-22107509 pdk upgrade gr

### PR DESCRIPTION
**Pull request by glenn-rodgers-sf**
# Writer's Quality Checklist

Before merging your PR, did you:

- [ ] Run spell checker
- [ ] Run link checker to check for broken xrefs
- [ ] Check for orphan files
- [ ] Perform a local build and do a final visual check of your content, including checking for:
  - Broken images
  - Dead links
  - Correct rendering of partials if they are used in your content
  - Formatting issues, such as:
    - Misnumbered ordered lists (steps) or incorrectly nested unordered lists
    - Messed up tables
    - Proper indentation
    - Correct header levels
- [ ] Receive final review and signoff from:
  - Technical SME
  - Product Manager
  - Editor or peer reviewer
  - Reporter, if this content is in response to a reported issue (internal or external feedback)
- [ ] If applicable, verify that the software actually got released

### CODE REVIEW

File: pdk/1.8/modules/ROOT/pages/policies-pdk-upgrade-pdk.adoc [hunk 1]
```diff
@@ -155,6 +155,110 @@ pub const POLICY_DIR: &str = concat!(env!("CARGO_MANIFEST_DIR"), "/target/wasm32
 ----
 . Save the `mod.rs` file.
 
+[[upgrade-anypoint-cli-pdk-plugin-earlier-1.8.0]]
+== Upgrade the Anypoint CLI PDK Plugin for Policies with Versions Earlier Than 1.8.0
+
+Depending on you configuration, when upgrading to 1.8.0 you might experience these issue:
```
Comment (tasmoore) [inline pdk/1.8/modules/ROOT/pages/policies-pdk-upgrade-pdk.adoc]:
```suggestion
Depending on you configuration, when upgrading to 1.8.0 you might experience these issues:
```

File: pdk/1.8/modules/ROOT/pages/policies-pdk-upgrade-pdk.adoc [hunk 2]
```diff
@@ -155,6 +155,110 @@ pub const POLICY_DIR: &str = concat!(env!("CARGO_MANIFEST_DIR"), "/target/wasm32
...
+
+* <<feature-compatibility-issue-on-tokio>>
+* <<compilation-error-structs>>
+
+[[feature-compatibility-issue-on-tokio]]
+=== Tokio Runtime Feature Compatibility Error
+
+When using a Tokio runtime for testing, you might receive a compilation error similar to the following when building for WebAssembly:
```
Comment (tasmoore) [inline pdk/1.8/modules/ROOT/pages/policies-pdk-upgrade-pdk.adoc]:
```suggestion
When using a Tokio runtime for testing, sometimes a compilation occurs similar to this error when building for WebAssembly:
```

File: pdk/1.8/modules/ROOT/pages/policies-pdk-upgrade-pdk.adoc [hunk 3]
```diff
@@ -155,6 +155,110 @@ pub const POLICY_DIR: &str = concat!(env!("CARGO_MANIFEST_DIR"), "/target/wasm32
...
+version = "1.0.0"
+rust-version = "1.88.0"
+edition = "2018"
+resolver = "2"
+----
+
+[[compilation-error-structs]]
+=== Compilation Error When Constructing Metadata-Related Structs
+
+When contruct Metadata-related structs, you might see an error similar to the following:
```
Comment (tasmoore) [inline pdk/1.8/modules/ROOT/pages/policies-pdk-upgrade-pdk.adoc]:
```suggestion
When constructing Metadata-related structs, sometimes an error similar to this one occurs:
```

File: pdk/1.8/modules/ROOT/pages/policies-pdk-upgrade-pdk.adoc [hunk 4]
```diff
@@ -155,6 +155,110 @@ pub const POLICY_DIR: &str = concat!(env!("CARGO_MANIFEST_DIR"), "/target/wasm32
...
+   |
+90 |                   flex_metadata: FlexMetadata {
+   |  ________________________________^
+91 | |                     flex_name: "test_flex_name".to_string(),
+92 | |                     flex_version: "1.0.0".to_string(),
+93 | |                 },
+   | |_________________^
+----
+
+PDK 1.8.0 marks metadata-related structs as `#[non_exhaustive]` so you can add new metadata fields without breaking changes.
```
Comment (tasmoore) [inline pdk/1.8/modules/ROOT/pages/policies-pdk-upgrade-pdk.adoc]:
```suggestion
PDK 1.8.0 marks metadata-related structs as `#[non_exhaustive]` so that you can add new metadata fields without breaking changes.
```

**Review by tasmoore — APPROVED** [review]
